# Generated by Django 4.1.5 on 2023-04-21 18:13

from django.db import migrations, models
import navsite.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        ('navsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='image',
            field=models.ImageField(blank=True, upload_to=navsite.abstract_models.category_image_path, verbose_name='image'),
        ),
    ]
