# Generated by Django 4.1.5 on 2023-06-09 01:34

from django.db import migrations, models
import django.utils.timezone
import navsite.abstract_models


class Migration(migrations.Migration):

    dependencies = [
        ('navsite', '0002_alter_categorytranslation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytranslation',
            name='active_url',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='is_catalog',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='categorytranslation',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='active_url',
            field=models.BooleanField(default=True, verbose_name='active_url'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('shop_grid', 'Shop Grid'), ('shop_list', 'Shop List'), ('external_link', 'External Link')], default='shop_grid', max_length=50, verbose_name='category type'),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=navsite.abstract_models.category_image_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_catalog',
            field=models.BooleanField(default=False, verbose_name='is_catalog'),
        ),
        migrations.AddField(
            model_name='category',
            name='order_number',
            field=models.IntegerField(default=0, verbose_name='order_number'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='url'),
        ),
    ]
