# Generated by Django 4.1.5 on 2023-06-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navsite', '0003_remove_categorytranslation_active_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_catalog',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order_number',
        ),
    ]
