# Generated by Django 4.1.5 on 2023-06-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navsite', '0004_remove_category_active_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='public',
        ),
    ]
