# Generated by Django 4.1.5 on 2023-05-19 22:13

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(default=banners.models.get_banner_type, max_length=16, verbose_name='banner_type'),
        ),
    ]
