# Generated by Django 4.1.5 on 2023-05-19 23:21

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to=banners.models.banner_directory_path),
        ),
    ]
