# Generated by Django 4.1.5 on 2023-05-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_alter_banner_options_banner_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannertranslation',
            old_name='promo_text',
            new_name='banner_text',
        ),
    ]
