# Generated by Django 4.1.5 on 2023-06-06 03:25

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230605_1821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='value',
        ),
        migrations.CreateModel(
            name='ProductVariationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.CharField(max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productvariation')),
            ],
            options={
                'unique_together': {('language_code', 'master', 'value')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.productattribute')),
            ],
            options={
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
