# Generated by Django 4.1.5 on 2023-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
