# Generated by Django 4.1.5 on 2023-06-13 21:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_producttranslation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='additional_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Description'),
        ),
    ]
