# Generated by Django 4.1.5 on 2023-01-16 08:19

import categories.abstract_models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Parent')),
                ('site', models.ForeignKey(blank=True, default=categories.abstract_models._get_current_site, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('tree_id', 'lft'),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='The slug is used in the URL of the page', max_length=100, verbose_name='slug')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='keywords')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='category_images', verbose_name='image')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('order_number', models.IntegerField(default=0, verbose_name='order_number')),
                ('url', models.CharField(blank=True, max_length=120, null=True, verbose_name='url')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('active_url', models.BooleanField(default=True, verbose_name='active_url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category Translation',
                'verbose_name_plural': 'Category Translations',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
