# Generated by Django 4.1.5 on 2023-04-25 01:24

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_logo', models.ImageField(blank=True, upload_to='images/logo/')),
                ('website_favicon', models.ImageField(blank=True, upload_to='images/favicon/')),
                ('website_email', models.EmailField(blank=True, max_length=120, null=True)),
                ('website_phone', models.CharField(blank=True, max_length=120, null=True)),
                ('website_address', models.CharField(blank=True, max_length=120, null=True)),
                ('website_facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('website_twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('website_instagram', models.CharField(blank=True, max_length=120, null=True)),
                ('website_youtube', models.CharField(blank=True, max_length=120, null=True)),
                ('website_whatsapp', models.CharField(blank=True, max_length=120, null=True)),
                ('website_telegram', models.CharField(blank=True, max_length=120, null=True)),
                ('website_pinterest', models.CharField(blank=True, max_length=120, null=True)),
                ('website_tiktok', models.CharField(blank=True, max_length=120, null=True)),
                ('website_vimeo', models.CharField(blank=True, max_length=120, null=True)),
                ('banner_type', models.CharField(choices=[('1', 'Banner 2 Modules'), ('2', 'Banner 3 Modules'), ('3', 'Banner 4 Modules'), ('4', 'Banner Promo 3'), ('5', 'Banner Promo 5')], default='1', max_length=1)),
                ('slider_width', models.CharField(blank=True, default='1780', max_length=6, null=True)),
                ('slider_height', models.CharField(blank=True, default='750', max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GlobalSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('website_title', models.CharField(blank=True, max_length=120, null=True)),
                ('website_description', models.CharField(blank=True, max_length=180, null=True)),
                ('website_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('website_copy_right', models.CharField(blank=True, max_length=120, null=True)),
                ('website_footer_text', models.CharField(blank=True, max_length=120, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='base.globalsettings')),
            ],
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='globalsettingstranslation',
            index=models.Index(fields=['id', 'language_code'], name='base_global_id_650fd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='globalsettingstranslation',
            unique_together={('language_code', 'master', 'id')},
        ),
    ]
