# Generated by Django 4.1.5 on 2023-04-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='website_ioverlander',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='website_linkedin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='website_tripadvisor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettingstranslation',
            name='website_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
