# Generated by Django 4.1.5 on 2023-04-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_globalsettings_website_ioverlander_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettingstranslation',
            name='website_footer_text',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
