# Generated by Django 4.1.5 on 2023-04-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_globalsettingstranslation_website_footer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettingstranslation',
            name='website_footer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
