# Generated by Django 4.1.5 on 2023-04-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_globalsettingstranslation_website_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='zoom',
            field=models.IntegerField(blank=True, default='12', null=True),
        ),
    ]
