# Generated by Django 4.1.5 on 2023-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_globalsettings_latitude_globalsettings_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=120, null=True)),
                ('google_analytics_api_key', models.CharField(blank=True, max_length=120, null=True)),
                ('twilio_sendgrid_api_key', models.CharField(blank=True, max_length=120, null=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=120, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=120, null=True)),
                ('exchange_rate_api_key', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Third Party Api Keys',
                'verbose_name_plural': 'Third Party Api Keys',
            },
        ),
    ]
