# Generated by Django 4.1.5 on 2023-04-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_thirdpartyapikeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyapikeys',
            name='twilio_sendgrid_sender_email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartyapikeys',
            name='twilio_sendgrid_sender_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
