# Generated by Django 4.1.5 on 2023-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_thirdpartyapikeys_twilio_sendgrid_sender_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('HNL', 'Lempira')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='free_delivery_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
