# Generated by Django 4.1.5 on 2023-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_globalsettings_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='banner_type',
            field=models.CharField(choices=[('Three', 'Two Banners'), ('Eleven', 'Two Attached Mirror Banners'), ('Seventeen', 'Two Separated Mirror Banners'), ('Four', 'Three Small Banners'), ('Fifteen', 'Three Big Banners'), ('Ten', 'Four Banners'), ('Six', 'Three Banners with Promo'), ('Five', 'Five Banners with Promo')], default='Four', max_length=16),
        ),
    ]
