# Generated by Django 4.1.5 on 2023-07-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('base', '0009_alter_globalsettings_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
