# Generated by Django 4.1.5 on 2023-07-12 03:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_globalsettings_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettingstranslation',
            name='website_about_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettingstranslation',
            name='website_our_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettingstranslation',
            name='website_our_mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettingstranslation',
            name='website_our_vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettingstranslation',
            name='website_privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettingstranslation',
            name='website_terms_and_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
