# Generated by Django 4.1.5 on 2023-07-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_globalsettingstranslation_website_about_us_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettingstranslation',
            old_name='website_copy_right',
            new_name='website_copyright',
        ),
    ]
