# Generated by Django 4.1.5 on 2023-07-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_website_copy_right_globalsettingstranslation_website_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettingstranslation',
            name='website_about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettingstranslation',
            name='website_privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettingstranslation',
            name='website_terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
