# Generated by Django 4.2.4 on 2023-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_globalsettingstranslation_website_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='website_favicon',
            field=models.FileField(blank=True, upload_to='images/favicon/'),
        ),
    ]
