# Generated by Django 4.1.5 on 2023-04-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertranslation',
            name='button_text',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='button_text'),
        ),
    ]
