# Generated by Django 4.1.5 on 2023-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_slidertranslation_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
