# Generated by Django 4.1.5 on 2023-05-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0003_alter_slider_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image_position',
            field=models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=6, verbose_name='image position'),
        ),
    ]
