# Generated by Django 4.1.5 on 2023-05-24 23:28

from django.db import migrations, models
import sliders.models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0004_slider_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=sliders.models.get_max_order_value, editable=False),
        ),
    ]
