# Generated by Django 4.1.5 on 2023-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0005_alter_slider_options_slider_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
