# Generated by Django 4.1.5 on 2023-06-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0006_alter_slider_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image_position',
            field=models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right'), ('full', 'Full Image')], default='center', max_length=6, verbose_name='image position'),
        ),
    ]
