# Generated by Django 4.1.5 on 2023-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timer',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
