# Generated by Django 4.1.5 on 2023-07-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_timer_active_timer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/countdowns')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
