# Generated by Django 4.1.5 on 2023-07-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_alter_countdown_image_alter_countdown_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
